### ISSUE TITLE
Help decide the show's length.

### ISSUE THREAD

**Issue by EdCharbeneau** [EdCharbeneau/BlazorStateHasChangedShow#1]
I have gotten pretty consistent feedback that the show should ideally be 1 hour long.

This conflicts with what I see on other popular Twitch streams (listed below) which average 2 - 3 hours in length and multiple episodes per week.

- [DevChatter](https://www.twitch.tv/devchatter)
- [CsharpFritz](https://www.twitch.tv/csharpfritz)
- [Noopkat](https://www.twitch.tv/noopkat)

Please keep in mind that November (aka Neural November) had a few extra long shows 4-5 hours that were a special series that went long to cover some "long shot" integration ideas. 4-5 hours isn't the normal target length.

**Comment by XanderStoffels** [comment]
I would think that a show of 2 to 3 hours should be fine. It really depends on the topic you're handling.
I'm currently watching you building a Blazor app from scratch, so it's no problem if it exceeds 1 hour 😄.

**Comment by EdCharbeneau** [comment]
Thanks for the feedback. Much appreciated.

**Comment by TomaszGrzmilas** [comment]
Great video. Thank you for that ! In my opinion, your videos are so interesting and helpful that the longer they are, the better ! Can't wait for another one ! BR

**Comment by EdCharbeneau** [comment]
@TomaszGrzmilas

Thanks so much for the kind words. Glad you're enjoying the show. I hope to find more opportunities to do interesting new content.

**Comment by EdCharbeneau** [comment]
Locking in the average show length at 2 hours +/- 10%
